name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
env:
  linked_services_path: ${{ github.workspace }}\data
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            if(Test-Path -Path $linked_services_path)
            {
              foreach($file in Get-ChildItem -Path $linked_services_path\*.json -Name)
              {
                $pipeline = Get-Content -Raw $linked_services_path\$file | ConvertFrom-Json
                echo $pipeline.name
              }
            }
            else
            {
                echo "Path doesn't exist."
            }
          azPSVersion: "latest"
      - name: Run iteration with powershell
        run: |
          foreach($file in Get-ChildItem -Path $linked_services_path\*.json -Name)
          {
            $pipeline = Get-Content -Raw $linked_services_path\$file | ConvertFrom-Json
            echo $pipeline.name
          }